create extension if not exists pgcrypto;

create table if not exists public.crm_users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique references auth.users(id) on delete set null,
  full_name text not null,
  email text not null unique,
  phone text not null default '',
  role text not null default 'user' check (role in ('admin', 'user')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint crm_users_ctnano_email check (lower(email) ~ '^[^@[:space:]]+@ctnano\.org$')
);

create table if not exists public.companies (
  id bigint generated by default as identity primary key,
  trade_name text not null,
  legal_name text not null default '',
  cnpj text not null default '',
  organization_type text not null default 'Empresa' check (organization_type in ('Empresa', 'Governo', 'Investidor', 'Outras')),
  mapping_date date,
  size text not null default 'Média',
  sector text not null default '',
  uf text not null default '',
  status text not null default 'Ativa',
  responsible_user_id bigint references public.crm_users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists companies_mapping_date_idx on public.companies (mapping_date desc);
create index if not exists companies_trade_name_idx on public.companies (trade_name);

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete restrict,
  name text not null,
  email text not null default '',
  phone text not null default '',
  role text not null default '',
  prospecting_date date,
  source text not null default 'Prospecção ativa',
  responsible_user_id bigint references public.crm_users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists contacts_company_id_idx on public.contacts (company_id);
create index if not exists contacts_prospecting_date_idx on public.contacts (prospecting_date desc);

create table if not exists public.opportunities (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete restrict,
  source_code text not null default '',
  title text not null,
  stage text not null default 'Proposta enviada' check (stage in ('Proposta enviada', 'Negociação', 'Contratada', 'Encerrada')),
  source_status text not null default '',
  loss_reason text not null default '',
  origin text not null default '',
  technical_team text not null default '',
  modality text not null default 'EMBRAPII CG',
  total_value numeric(16,2) not null default 0,
  company_value numeric(16,2) not null default 0,
  economic_value numeric(16,2) not null default 0,
  embrapii_value numeric(16,2) not null default 0,
  probability integer not null default 10 check (probability between 0 and 100),
  owner text not null default '',
  responsible_user_id bigint references public.crm_users(id) on delete set null,
  uf text not null default '',
  proposal_date date,
  sent_date date,
  accepted_date date,
  contract_date date,
  negotiation_days integer not null default 0 check (negotiation_days >= 0),
  contracting_days integer not null default 0 check (contracting_days >= 0),
  next_step text not null default '',
  due_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint opportunity_contract_date_rule check (contract_date is null or stage = 'Contratada')
);
create index if not exists opportunities_company_id_idx on public.opportunities (company_id);
create index if not exists opportunities_sent_date_idx on public.opportunities (sent_date desc);
create index if not exists opportunities_contract_date_idx on public.opportunities (contract_date desc);

create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  opportunity_id bigint references public.opportunities(id) on delete set null,
  company_id bigint references public.companies(id) on delete set null,
  type text not null default 'Tarefa',
  title text not null,
  due_date date,
  owner text not null default '',
  responsible_user_id bigint references public.crm_users(id) on delete set null,
  status text not null default 'Pendente',
  notes text not null default '',
  created_at timestamptz not null default now()
);
create index if not exists activities_due_date_idx on public.activities (due_date);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  opportunity_id bigint references public.opportunities(id) on delete set null,
  company_id bigint not null references public.companies(id) on delete restrict,
  name text not null,
  status text not null default 'Handover',
  start_date date,
  end_date date,
  manager text not null default '',
  responsible_user_id bigint references public.crm_users(id) on delete set null,
  handover_progress integer not null default 0 check (handover_progress between 0 and 100),
  total_value numeric(16,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.kpis (
  id bigint generated by default as identity primary key,
  key text not null unique,
  label text not null,
  unit text not null default 'Unidade',
  direction text not null default 'Quanto maior, melhor',
  weight numeric(2,0) not null default 3 check (weight between 1 and 5),
  measurement_method text not null default 'Apuração manual',
  responsible_user_id bigint references public.crm_users(id) on delete set null,
  show_on_dashboard boolean not null default false,
  targets jsonb not null default '[]'::jsonb,
  manual_actual_2026 numeric not null default 0,
  manual_actual_2027 numeric not null default 0,
  manual_actual_2028 numeric not null default 0,
  target_2026 numeric not null default 0,
  target_2027 numeric not null default 0,
  target_2028 numeric not null default 0
);

create table if not exists public.backups (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  status text not null,
  file_name text not null,
  drive_file_id text
);

create or replace function public.protect_primary_crm_admin()
returns trigger
language plpgsql
as $$
begin
  if lower(old.email) = 'ricardo.neres@ctnano.org' then
    new.email := old.email;
    new.role := 'admin';
    new.active := true;
  end if;
  return new;
end;
$$;

drop trigger if exists protect_primary_crm_admin_row on public.crm_users;
create trigger protect_primary_crm_admin_row
  before update on public.crm_users
  for each row execute procedure public.protect_primary_crm_admin();

create or replace function public.handle_new_crm_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  normalized_email text := lower(coalesce(new.email, ''));
begin
  if normalized_email !~ '^[^@[:space:]]+@ctnano\.org$' then
    raise exception 'Somente e-mails @ctnano.org podem acessar o CTNano CRM';
  end if;
  insert into public.crm_users (auth_user_id, full_name, email, phone, role, active)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'full_name'), ''), split_part(normalized_email, '@', 1)),
    normalized_email,
    coalesce(new.raw_user_meta_data ->> 'phone', ''),
    case when normalized_email = 'ricardo.neres@ctnano.org' then 'admin' else 'user' end,
    true
  )
  on conflict (email) do update set
    auth_user_id = excluded.auth_user_id,
    full_name = case when public.crm_users.full_name = '' then excluded.full_name else public.crm_users.full_name end,
    phone = case when public.crm_users.phone = '' then excluded.phone else public.crm_users.phone end,
    role = case when normalized_email = 'ricardo.neres@ctnano.org' then 'admin' else public.crm_users.role end,
    active = true;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_ctnano_crm on auth.users;
create trigger on_auth_user_created_ctnano_crm
  after insert on auth.users
  for each row execute procedure public.handle_new_crm_user();

insert into public.crm_users (full_name, email, role, active)
values ('Ricardo Neres', 'ricardo.neres@ctnano.org', 'admin', true)
on conflict (email) do update set role = 'admin', active = true;

insert into public.kpis (key, label, unit, direction, weight, measurement_method, show_on_dashboard, targets, target_2026, target_2027, target_2028) values
  ('mapped_companies', 'Empresas mapeadas', 'Unidade', 'Quanto maior, melhor', 3, 'Organizações do tipo Empresa cadastradas no ano', true, '[{"year":2026,"target":0,"manualActual":0},{"year":2027,"target":0,"manualActual":0},{"year":2028,"target":0,"manualActual":0}]', 0, 0, 0),
  ('prospected_companies', 'Empresas prospectadas', 'Unidade', 'Quanto maior, melhor', 3, 'Contatos prospectados no ano', true, '[{"year":2026,"target":84,"manualActual":0},{"year":2027,"target":98,"manualActual":0},{"year":2028,"target":112,"manualActual":0}]', 84, 98, 112),
  ('technical_proposals', 'Propostas técnicas', 'Unidade', 'Quanto maior, melhor', 3, 'Propostas técnicas enviadas no ano', true, '[{"year":2026,"target":18,"manualActual":0},{"year":2027,"target":19,"manualActual":0},{"year":2028,"target":20,"manualActual":0}]', 18, 19, 20),
  ('contracted_projects', 'Projetos contratados', 'Unidade', 'Quanto maior, melhor', 3, 'Projetos contratados no ano', true, '[{"year":2026,"target":6,"manualActual":0},{"year":2027,"target":7,"manualActual":0},{"year":2028,"target":8,"manualActual":0}]', 6, 7, 8),
  ('contracting_companies', 'Empresas contratantes', 'Unidade', 'Quanto maior, melhor', 3, 'Empresas contratantes únicas no ano', true, '[{"year":2026,"target":5,"manualActual":0},{"year":2027,"target":6,"manualActual":0},{"year":2028,"target":7,"manualActual":0}]', 5, 6, 7),
  ('mpe_startup', 'Startups/MPEs contratantes', 'Unidade', 'Quanto maior, melhor', 3, 'Startups/MPEs contratantes no ano', false, '[{"year":2026,"target":2,"manualActual":0},{"year":2027,"target":2,"manualActual":0},{"year":2028,"target":2,"manualActual":0}]', 2, 2, 2),
  ('company_events', 'Eventos com empresas', 'Unidade', 'Quanto maior, melhor', 3, 'Apuração manual', false, '[{"year":2026,"target":3,"manualActual":0},{"year":2027,"target":3,"manualActual":0},{"year":2028,"target":3,"manualActual":0}]', 3, 3, 3),
  ('pi_requests', 'Pedidos de PI', 'Unidade', 'Quanto maior, melhor', 3, 'Apuração manual', false, '[{"year":2026,"target":3,"manualActual":0},{"year":2027,"target":3,"manualActual":0},{"year":2028,"target":4,"manualActual":0}]', 3, 3, 4),
  ('satisfaction', 'Satisfação das empresas', 'Unidade', 'Quanto maior, melhor', 3, 'Apuração manual', false, '[{"year":2026,"target":8,"manualActual":0},{"year":2027,"target":8,"manualActual":0},{"year":2028,"target":8,"manualActual":0}]', 8, 8, 8),
  ('average_negotiation_time', 'Tempo médio de negociação', 'Outro', 'Quanto menor, melhor', 3, 'Tempo médio de negociação concluída no ano', false, '[]', 0, 0, 0),
  ('average_contracting_time', 'Tempo médio de contratação', 'Outro', 'Quanto menor, melhor', 3, 'Tempo médio de contratação concluída no ano', false, '[]', 0, 0, 0)
on conflict (key) do nothing;

create or replace function public.is_active_ctnano_user()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.crm_users where auth_user_id = auth.uid() and active); $$;

alter table public.crm_users enable row level security;
alter table public.companies enable row level security;
alter table public.contacts enable row level security;
alter table public.opportunities enable row level security;
alter table public.activities enable row level security;
alter table public.projects enable row level security;
alter table public.kpis enable row level security;
alter table public.backups enable row level security;

drop policy if exists "active users read crm_users" on public.crm_users;
create policy "active users read crm_users" on public.crm_users for select to authenticated using (public.is_active_ctnano_user());
drop policy if exists "active users read companies" on public.companies;
create policy "active users read companies" on public.companies for select to authenticated using (public.is_active_ctnano_user());
drop policy if exists "active users read contacts" on public.contacts;
create policy "active users read contacts" on public.contacts for select to authenticated using (public.is_active_ctnano_user());
drop policy if exists "active users read opportunities" on public.opportunities;
create policy "active users read opportunities" on public.opportunities for select to authenticated using (public.is_active_ctnano_user());
drop policy if exists "active users read activities" on public.activities;
create policy "active users read activities" on public.activities for select to authenticated using (public.is_active_ctnano_user());
drop policy if exists "active users read projects" on public.projects;
create policy "active users read projects" on public.projects for select to authenticated using (public.is_active_ctnano_user());
drop policy if exists "active users read kpis" on public.kpis;
create policy "active users read kpis" on public.kpis for select to authenticated using (public.is_active_ctnano_user());
drop policy if exists "admins read backups" on public.backups;
create policy "admins read backups" on public.backups for select to authenticated using (exists (select 1 from public.crm_users where auth_user_id = auth.uid() and active and role = 'admin'));
